@url = https://8080-rose-urial-q8qj44x4.ws-us20.gitpod.io
###
GET {{url}}/filmes

###

POST https://8080-rose-urial-q8qj44x4.ws-us20.gitpod.io/filmes
Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###
PUT https://8080-rose-urial-q8qj44x4.ws-us20.gitpod.io/filmes/5
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}

###
DELETE https://8080-rose-urial-q8qj44x4.ws-us20.gitpod.io/filmes
Content-Type: application/json

{
    "id" : 5
}