GET https://8080-beige-panther-9pl3bjmg.ws-us18.gitpod.io/filmes

###

POST https://8080-beige-panther-9pl3bjmg.ws-us18.gitpod.io/filmes
Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###
PUT https://8080-beige-panther-9pl3bjmg.ws-us18.gitpod.io/filmes/5
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}